services:
  pm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - pm-data:/app/backend/data

volumes:
  pm-data:
